### ISSUE TITLE
Not formatting 100,000 correctly

### ISSUE THREAD

**Issue by tom-fitz** [cod-e-ash/amount-in-words#3]
**Issue**
- Trying to convert 100,000.00 to One Hundred Thousand Dollars

**Steps to reproduce**
- `console.log("wordLib: ", atw.toWords("100,000.00", CountryCodes.USA));`

**Result**
- `One Hundred Dollars`

**Comment by cod-e-ash** [comment]
Fixed

**Comment by tom-fitz** [comment]
> Fixed

I'm not seeing this be fixed. Did you update that NPM package?

**Comment by 6sigmadc** [comment]
> > Fixed
> 
> I'm not seeing this be fixed. Did you update that NPM package?

There are no underlying dependencies. So no packages to update.

**Comment by tom-fitz** [comment]
Ok, so why am I still seeing the bug and not the correct output?

*- Thomas Fitzgerald*
